// <auto-generated />
namespace WCF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class currentclasspropertyinStudentmodelrefactored : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(currentclasspropertyinStudentmodelrefactored));
        
        string IMigrationMetadata.Id
        {
            get { return "201601150547534_current-class property in Student model refactored"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
