//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.UnivercityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentsList", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class StudentsList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.Student[] StudentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.Student[] Students {
            get {
                return this.StudentsField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentsField, value) != true)) {
                    this.StudentsField = value;
                    this.RaisePropertyChanged("Students");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCF.Model")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.Course[] CoursesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EnrollmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.SexEnum SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.Course[] Courses {
            get {
                return this.CoursesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoursesField, value) != true)) {
                    this.CoursesField = value;
                    this.RaisePropertyChanged("Courses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentClass {
            get {
                return this.CurrentClassField;
            }
            set {
                if ((this.CurrentClassField.Equals(value) != true)) {
                    this.CurrentClassField = value;
                    this.RaisePropertyChanged("CurrentClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EnrollmentDate {
            get {
                return this.EnrollmentDateField;
            }
            set {
                if ((this.EnrollmentDateField.Equals(value) != true)) {
                    this.EnrollmentDateField = value;
                    this.RaisePropertyChanged("EnrollmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionId {
            get {
                return this.SectionIdField;
            }
            set {
                if ((this.SectionIdField.Equals(value) != true)) {
                    this.SectionIdField = value;
                    this.RaisePropertyChanged("SectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.SexEnum Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/WCF.Model")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.Student[] StudentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.Teacher[] TeachersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Credits {
            get {
                return this.CreditsField;
            }
            set {
                if ((this.CreditsField.Equals(value) != true)) {
                    this.CreditsField = value;
                    this.RaisePropertyChanged("Credits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionId {
            get {
                return this.SectionIdField;
            }
            set {
                if ((this.SectionIdField.Equals(value) != true)) {
                    this.SectionIdField = value;
                    this.RaisePropertyChanged("SectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.Student[] Students {
            get {
                return this.StudentsField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentsField, value) != true)) {
                    this.StudentsField = value;
                    this.RaisePropertyChanged("Students");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.Teacher[] Teachers {
            get {
                return this.TeachersField;
            }
            set {
                if ((object.ReferenceEquals(this.TeachersField, value) != true)) {
                    this.TeachersField = value;
                    this.RaisePropertyChanged("Teachers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SexEnum", Namespace="http://schemas.datacontract.org/2004/07/WCF.Model")]
    public enum SexEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Man = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Women = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/WCF.Model")]
    [System.SerializableAttribute()]
    public partial class Teacher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.Course[] CoursesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.GradeEnum GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.Section[] SectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.SexEnum SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.Course[] Courses {
            get {
                return this.CoursesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoursesField, value) != true)) {
                    this.CoursesField = value;
                    this.RaisePropertyChanged("Courses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.GradeEnum Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.Section[] Sections {
            get {
                return this.SectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionsField, value) != true)) {
                    this.SectionsField = value;
                    this.RaisePropertyChanged("Sections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.SexEnum Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GradeEnum", Namespace="http://schemas.datacontract.org/2004/07/WCF.Model")]
    public enum GradeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Master = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Doctorat = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Section", Namespace="http://schemas.datacontract.org/2004/07/WCF.Model")]
    [System.SerializableAttribute()]
    public partial class Section : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.UnivercityService.Teacher[] TeachersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultyId {
            get {
                return this.FacultyIdField;
            }
            set {
                if ((this.FacultyIdField.Equals(value) != true)) {
                    this.FacultyIdField = value;
                    this.RaisePropertyChanged("FacultyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.UnivercityService.Teacher[] Teachers {
            get {
                return this.TeachersField;
            }
            set {
                if ((object.ReferenceEquals(this.TeachersField, value) != true)) {
                    this.TeachersField = value;
                    this.RaisePropertyChanged("Teachers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnivercityService.IUnivercityService")]
    public interface IUnivercityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/TryLogin", ReplyAction="http://tempuri.org/IUnivercityService/TryLoginResponse")]
        bool TryLogin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/TryLogin", ReplyAction="http://tempuri.org/IUnivercityService/TryLoginResponse")]
        System.Threading.Tasks.Task<bool> TryLoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetStudentsList", ReplyAction="http://tempuri.org/IUnivercityService/GetStudentsListResponse")]
        WPF.UnivercityService.StudentsList GetStudentsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetStudentsList", ReplyAction="http://tempuri.org/IUnivercityService/GetStudentsListResponse")]
        System.Threading.Tasks.Task<WPF.UnivercityService.StudentsList> GetStudentsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/AddStudent", ReplyAction="http://tempuri.org/IUnivercityService/AddStudentResponse")]
        int AddStudent(WPF.UnivercityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/AddStudent", ReplyAction="http://tempuri.org/IUnivercityService/AddStudentResponse")]
        System.Threading.Tasks.Task<int> AddStudentAsync(WPF.UnivercityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/DeleteStudent", ReplyAction="http://tempuri.org/IUnivercityService/DeleteStudentResponse")]
        bool DeleteStudent(int StudentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/DeleteStudent", ReplyAction="http://tempuri.org/IUnivercityService/DeleteStudentResponse")]
        System.Threading.Tasks.Task<bool> DeleteStudentAsync(int StudentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/ModifyStudent", ReplyAction="http://tempuri.org/IUnivercityService/ModifyStudentResponse")]
        bool ModifyStudent(WPF.UnivercityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/ModifyStudent", ReplyAction="http://tempuri.org/IUnivercityService/ModifyStudentResponse")]
        System.Threading.Tasks.Task<bool> ModifyStudentAsync(WPF.UnivercityService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetTeachersList", ReplyAction="http://tempuri.org/IUnivercityService/GetTeachersListResponse")]
        bool GetTeachersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetTeachersList", ReplyAction="http://tempuri.org/IUnivercityService/GetTeachersListResponse")]
        System.Threading.Tasks.Task<bool> GetTeachersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetCoursesList", ReplyAction="http://tempuri.org/IUnivercityService/GetCoursesListResponse")]
        bool GetCoursesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetCoursesList", ReplyAction="http://tempuri.org/IUnivercityService/GetCoursesListResponse")]
        System.Threading.Tasks.Task<bool> GetCoursesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetFacultiesList", ReplyAction="http://tempuri.org/IUnivercityService/GetFacultiesListResponse")]
        bool GetFacultiesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetFacultiesList", ReplyAction="http://tempuri.org/IUnivercityService/GetFacultiesListResponse")]
        System.Threading.Tasks.Task<bool> GetFacultiesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetSectionsList", ReplyAction="http://tempuri.org/IUnivercityService/GetSectionsListResponse")]
        bool GetSectionsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetSectionsList", ReplyAction="http://tempuri.org/IUnivercityService/GetSectionsListResponse")]
        System.Threading.Tasks.Task<bool> GetSectionsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetStudentsNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetStudentsNumberResponse")]
        int GetStudentsNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetStudentsNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetStudentsNumberResponse")]
        System.Threading.Tasks.Task<int> GetStudentsNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetTeachersNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetTeachersNumberResponse")]
        int GetTeachersNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetTeachersNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetTeachersNumberResponse")]
        System.Threading.Tasks.Task<int> GetTeachersNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetCoursesNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetCoursesNumberResponse")]
        int GetCoursesNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetCoursesNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetCoursesNumberResponse")]
        System.Threading.Tasks.Task<int> GetCoursesNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetSectionsNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetSectionsNumberResponse")]
        int GetSectionsNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetSectionsNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetSectionsNumberResponse")]
        System.Threading.Tasks.Task<int> GetSectionsNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetFacultiesNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetFacultiesNumberResponse")]
        int GetFacultiesNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnivercityService/GetFacultiesNumber", ReplyAction="http://tempuri.org/IUnivercityService/GetFacultiesNumberResponse")]
        System.Threading.Tasks.Task<int> GetFacultiesNumberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnivercityServiceChannel : WPF.UnivercityService.IUnivercityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnivercityServiceClient : System.ServiceModel.ClientBase<WPF.UnivercityService.IUnivercityService>, WPF.UnivercityService.IUnivercityService {
        
        public UnivercityServiceClient() {
        }
        
        public UnivercityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnivercityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnivercityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnivercityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TryLogin(string email, string password) {
            return base.Channel.TryLogin(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> TryLoginAsync(string email, string password) {
            return base.Channel.TryLoginAsync(email, password);
        }
        
        public WPF.UnivercityService.StudentsList GetStudentsList() {
            return base.Channel.GetStudentsList();
        }
        
        public System.Threading.Tasks.Task<WPF.UnivercityService.StudentsList> GetStudentsListAsync() {
            return base.Channel.GetStudentsListAsync();
        }
        
        public int AddStudent(WPF.UnivercityService.Student student) {
            return base.Channel.AddStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentAsync(WPF.UnivercityService.Student student) {
            return base.Channel.AddStudentAsync(student);
        }
        
        public bool DeleteStudent(int StudentId) {
            return base.Channel.DeleteStudent(StudentId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStudentAsync(int StudentId) {
            return base.Channel.DeleteStudentAsync(StudentId);
        }
        
        public bool ModifyStudent(WPF.UnivercityService.Student student) {
            return base.Channel.ModifyStudent(student);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyStudentAsync(WPF.UnivercityService.Student student) {
            return base.Channel.ModifyStudentAsync(student);
        }
        
        public bool GetTeachersList() {
            return base.Channel.GetTeachersList();
        }
        
        public System.Threading.Tasks.Task<bool> GetTeachersListAsync() {
            return base.Channel.GetTeachersListAsync();
        }
        
        public bool GetCoursesList() {
            return base.Channel.GetCoursesList();
        }
        
        public System.Threading.Tasks.Task<bool> GetCoursesListAsync() {
            return base.Channel.GetCoursesListAsync();
        }
        
        public bool GetFacultiesList() {
            return base.Channel.GetFacultiesList();
        }
        
        public System.Threading.Tasks.Task<bool> GetFacultiesListAsync() {
            return base.Channel.GetFacultiesListAsync();
        }
        
        public bool GetSectionsList() {
            return base.Channel.GetSectionsList();
        }
        
        public System.Threading.Tasks.Task<bool> GetSectionsListAsync() {
            return base.Channel.GetSectionsListAsync();
        }
        
        public int GetStudentsNumber() {
            return base.Channel.GetStudentsNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetStudentsNumberAsync() {
            return base.Channel.GetStudentsNumberAsync();
        }
        
        public int GetTeachersNumber() {
            return base.Channel.GetTeachersNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetTeachersNumberAsync() {
            return base.Channel.GetTeachersNumberAsync();
        }
        
        public int GetCoursesNumber() {
            return base.Channel.GetCoursesNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetCoursesNumberAsync() {
            return base.Channel.GetCoursesNumberAsync();
        }
        
        public int GetSectionsNumber() {
            return base.Channel.GetSectionsNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetSectionsNumberAsync() {
            return base.Channel.GetSectionsNumberAsync();
        }
        
        public int GetFacultiesNumber() {
            return base.Channel.GetFacultiesNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetFacultiesNumberAsync() {
            return base.Channel.GetFacultiesNumberAsync();
        }
    }
}
